services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: peril_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    profiles:
      - infra
    restart: on-failure