# https://taskfile.dev

version: '3'

dotenv: ['.env']

tasks:
  setup:
    desc: Setup Project
    cmds:
      - go mod download

  start:server:
    desc: Start the Peril Server
    cmds:
      - go run ./cmd/server

  start:client:
    desc: Start the Peril Client
    cmds:
      - go run ./cmd/client
  
  up:
    desc: Setup the infrastructure
    cmds:
      - docker compose --profile infra up --wait
  
  stop:
    desc: Stop the infrastructure
    cmds:
      - docker compose --profile infra stop

  down:
    desc: Teardown the infrastructure
    cmds:
      - docker compose --profile infra down --timeout 0
